### ISSUE TITLE
[F] Suggest words automatically

### ISSUE THREAD

**Issue by fabianski7** [qownnotes/scripts#124]
#### Script name
[dictionary-autocomplete](https://github.com/qownnotes/scripts/tree/master/dictionary-autocomplete)

#### Script authors
@pbek

#### Actual behaviour
I currently use this script to correct words using the CTRL+Space shortcut, but this becomes extremely repetitive when I am writing a large file.

#### Expected behaviour
My suggestion is to allow the script to run automatically (without having to use the keyboard shortcut) whenever a word starts to be typed.

This could be identified when a sequence of words is inserted. 
Ex.: When inserting three words together, the QON would activate the script and it will show the same suggestions as the shortcut CTRL+Space.

This behavior is quite similar to what we already have in Android.

**Comment by pbek** [comment]
I'm sorry, there is no scripting hook that would allow this and implementing a hook that triggers on every keypress and then implementing a script that searches a large dictionary on every keypress wouldn't be very performant...

**Comment by pbek** [comment]
any other oppinnion, @Waqar144?

**Comment by Waqar144** [comment]
- if this were to be implemented, it needs to be configurable somehow otherwise it will just some annoy users and they will ask for it to be configurable. 
- and yes, to do this with good performance we will probably need to do it natively..

But the idea is good, and would be helpful to some users. 

Also, we will need the user to specify some autocomplete dictionary so that we don't have to lookup *all* available dictionaries.

We can, however, leverage sonnet API to provide some automated guessing but that already (most of the times) uses the dictionary to guess the language so not sure if using sonnet with auto detection will be helpful.

**Comment by fabianski7** [comment]
seems a bit difficult 🥲

**Comment by Beurt** [comment]
Hi,

Very interesting idea!

I think that many scripts would profit if the script API had access to an edit suggestions dropdown list (maybe using [QCompleter](https://doc.qt.io/qt-5/qcompleter.html#basic-usage)? I found that here: [`How to accomplish drop down word suggestions in Qt?`](https://stackoverflow.com/questions/24248606/how-to-accomplish-drop-down-word-suggestions-in-qt)).
