### ISSUE TITLE
note-link-to-clipboard script cannot handle multibyte filename

### ISSUE THREAD

**Issue by piyo-gh** [qownnotes/scripts#26]
I'm using Windows 10 on Japanese locale.
note-link-to-clipboard script replace any multibyte charactor of filename to `_`.

This problem doesn't happen when I use `insert link`.

**Comment by pbek** [comment]
@Maboroshy, that script was your handiwork, right?

**Comment by Maboroshy** [comment]
Yep, that's mine. I'll see if I can do something about it.

**Comment by pbek** [comment]
Be sure of the applause of the masses! 😁

**Comment by Maboroshy** [comment]
There was the issue with the regexp. QON uses ` [^\d\w]` with `UseUnicodePropertiesOption` so Japanese would fit into `\w`, but there's no such option for QML. I had to use an ugly long regex to emulate QON's behaviour. At least Japanese links works correctly on my machine.

Maybe regex in QON should be reconsidered so it would replace only characters that are not allowed in Windows file names, instead of all the puncture marks there are in the world.

Please test the new version of the script from repository.

**Comment by pbek** [comment]
I will close this issue until there is more information.
